-- ZenFlow: профиль специалиста + расходы
-- Выполнить в Supabase → SQL Editor → Run (после предыдущих schema-файлов)

-- Профиль — привязан к учётной записи (auth.users), редактируется в Настройках
create table profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text default '',
  role text default 'Специалист',
  phone text default '',
  updated_at timestamptz default now()
);

alter table profiles enable row level security;
create policy "select own profile" on profiles for select using (auth.uid() = id);
create policy "update own profile" on profiles for update using (auth.uid() = id);
create policy "insert own profile" on profiles for insert with check (auth.uid() = id);

-- Автоматически создаём строку профиля при регистрации нового пользователя
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, name)
  values (new.id, coalesce(split_part(new.email, '@', 1), 'Специалист'));
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Расходы — для реальных финансов (доход считаем прямо из appointments)
create table expenses (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text default '',
  amount integer not null default 0,
  date date not null default current_date,
  created_at timestamptz default now()
);

alter table expenses enable row level security;
create policy "allow all - expenses" on expenses for all using (true) with check (true);

insert into expenses (title, subtitle, amount, date) values
('Расходники', 'Масло, полотенца', 2000, current_date),
('Аренда кабинета', 'Ежемесячный платёж', 3200, current_date);
