-- ZenFlow: схема базы данных под клиентов
-- Выполнить целиком в Supabase → SQL Editor → Run

create table clients (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  initials text,
  visits integer default 0,
  cancellations integer default 0,
  avg_check integer default 0,
  last_visit text,
  favorite_service text,
  color text,
  created_at timestamptz default now()
);

create table client_history (
  id bigint generated by default as identity primary key,
  client_id bigint references clients(id) on delete cascade,
  date text,
  service text,
  color text,
  price integer
);

create table client_payments (
  id bigint generated by default as identity primary key,
  client_id bigint references clients(id) on delete cascade,
  date text,
  amount integer,
  method text
);

create table client_notes (
  id bigint generated by default as identity primary key,
  client_id bigint references clients(id) on delete cascade,
  date text,
  text text
);

create table client_recommendations (
  client_id bigint primary key references clients(id) on delete cascade,
  text text
);

-- Пока нет авторизации специалиста — разрешаем чтение/запись всем,
-- кто обращается с публичным (anon) ключом. Когда добавим вход по
-- Email/Apple ID, эти политики нужно будет сузить до "только свои записи".
alter table clients enable row level security;
alter table client_history enable row level security;
alter table client_payments enable row level security;
alter table client_notes enable row level security;
alter table client_recommendations enable row level security;

create policy "allow all - clients" on clients for all using (true) with check (true);
create policy "allow all - client_history" on client_history for all using (true) with check (true);
create policy "allow all - client_payments" on client_payments for all using (true) with check (true);
create policy "allow all - client_notes" on client_notes for all using (true) with check (true);
create policy "allow all - client_recommendations" on client_recommendations for all using (true) with check (true);

-- Демо-данные — те же 7 клиентов, что были моками
insert into clients (name, phone, initials, visits, cancellations, avg_check, last_visit, favorite_service, color) values
('Марина Соколова', '+7 916 111-11-11', 'МС', 22, 0, 4200, 'сегодня, 09:00', 'Классический массаж', '#7C9A86'),
('Игорь Плетнёв', '+7 916 222-22-22', 'ИП', 9, 1, 5200, 'сегодня, 10:30', 'Спортивный массаж', '#B98572'),
('Анна Ким', '+7 916 000-00-00', 'АК', 14, 0, 3800, 'сегодня, 13:00', 'Лимфодренаж', '#9C8FB0'),
('Дарья Ефимова', '+7 916 333-33-33', 'ДЕ', 3, 0, 2800, 'сегодня, 14:00', 'Массаж лица', '#C6A15B'),
('Олег Крылов', '+7 916 444-44-44', 'ОК', 6, 2, 4200, 'сегодня, 16:30', 'Классический массаж', '#7C9A86'),
('Света Волкова', '+7 916 555-55-55', 'СВ', 4, 2, 3800, '9 месяцев назад', 'Лимфодренаж', '#9C8FB0'),
('Павел Гриб', '+7 916 666-66-66', 'ПГ', 11, 0, 5200, '3 недели назад', 'Спортивный массаж', '#B98572');

-- Заметки и рекомендации для Анны Ким (id подставится автоматически по имени)
insert into client_notes (client_id, date, text)
select id, '31 июл', 'Просит поменьше давления в области поясницы.' from clients where name = 'Анна Ким'
union all
select id, '14 июл', 'Хорошо реагирует на тёплое масло, любит тишину во время сессии.' from clients where name = 'Анна Ким';

insert into client_recommendations (client_id, text)
select id, 'Рекомендовать курс из 4 сеансов лимфодренажа с интервалом 2 недели. Обратить внимание на поясничную область — просила снизить давление на последнем сеансе.'
from clients where name = 'Анна Ким';
