-- RITENA client deposit / balance ledger
-- Keeps customer deposits separate from service revenue.

create table if not exists public.client_balance_transactions (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  appointment_id bigint references public.appointments(id) on delete set null,
  amount integer not null check (amount <> 0),
  kind text not null check (kind in ('deposit','use','adjustment')),
  method text,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists client_balance_transactions_owner_idx on public.client_balance_transactions(owner_id);
create index if not exists client_balance_transactions_client_idx on public.client_balance_transactions(client_id);
create index if not exists client_balance_transactions_appointment_idx on public.client_balance_transactions(appointment_id);

alter table public.client_balance_transactions enable row level security;
revoke all on table public.client_balance_transactions from anon;
grant select, insert on table public.client_balance_transactions to authenticated;
grant usage, select on sequence public.client_balance_transactions_id_seq to authenticated;

create policy "own client balance transactions select"
on public.client_balance_transactions for select to authenticated
using (
  owner_id = (select auth.uid())
  and exists (select 1 from public.clients c where c.id = client_id and c.owner_id = (select auth.uid()))
);

create policy "own client balance transactions insert"
on public.client_balance_transactions for insert to authenticated
with check (
  owner_id = (select auth.uid())
  and exists (select 1 from public.clients c where c.id = client_id and c.owner_id = (select auth.uid()))
  and (
    appointment_id is null
    or exists (
      select 1 from public.appointments a
      where a.id = appointment_id
        and a.owner_id = (select auth.uid())
        and a.client_id = client_id
    )
  )
);

create or replace function public.complete_appointment_with_balance(
  p_appointment_id bigint,
  p_service_total integer,
  p_method text,
  p_received integer default null,
  p_use_balance boolean default true,
  p_keep_change boolean default false
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_appointment public.appointments%rowtype;
  v_balance integer := 0;
  v_used integer := 0;
  v_due integer := 0;
  v_received integer := 0;
  v_change integer := 0;
  v_deposit integer := 0;
  v_method_label text;
  v_existing_payment_id bigint;
  v_today text := to_char(timezone('Asia/Novosibirsk', now()), 'YYYY-MM-DD');
begin
  if p_service_total is null or p_service_total < 0 then raise exception 'Некорректная сумма услуги'; end if;

  select a.* into v_appointment from public.appointments a where a.id = p_appointment_id for update;
  if not found then raise exception 'Запись не найдена'; end if;

  perform 1 from public.clients c where c.id = v_appointment.client_id for update;

  select cp.id into v_existing_payment_id
  from public.client_payments cp
  where cp.appointment_id = p_appointment_id
  order by cp.id desc limit 1;

  select coalesce(sum(t.amount), 0)::integer into v_balance
  from public.client_balance_transactions t
  where t.client_id = v_appointment.client_id;

  if v_existing_payment_id is not null then
    return jsonb_build_object('already_paid',true,'balance_before',v_balance,'used_balance',0,'amount_due',0,'received',0,'change',0,'deposited',0,'balance_after',v_balance);
  end if;

  if p_use_balance then v_used := least(greatest(v_balance, 0), p_service_total); end if;
  v_due := p_service_total - v_used;

  if p_method = 'Наличные' then
    v_received := coalesce(p_received, v_due);
    if v_received < v_due then raise exception 'Недостаточно наличных: нужно %', v_due; end if;
    v_change := greatest(v_received - v_due, 0);
    if p_keep_change then v_deposit := v_change; end if;
  else
    v_received := v_due;
  end if;

  update public.appointments set status='done', price=p_service_total, full_price=p_service_total where id=p_appointment_id;

  if v_used > 0 then
    insert into public.client_balance_transactions(owner_id,client_id,appointment_id,amount,kind,method,note)
    values ((select auth.uid()),v_appointment.client_id,p_appointment_id,-v_used,'use','Баланс','Списано в оплату сеанса');
  end if;

  if v_deposit > 0 then
    insert into public.client_balance_transactions(owner_id,client_id,appointment_id,amount,kind,method,note)
    values ((select auth.uid()),v_appointment.client_id,p_appointment_id,v_deposit,'deposit',p_method,'Сдача оставлена на следующий сеанс');
  end if;

  v_method_label := case
    when v_used > 0 and v_due > 0 then format('Баланс %s ₽ + %s %s ₽',v_used,p_method,v_due)
    when v_used > 0 and v_due = 0 then format('Баланс %s ₽',v_used)
    else p_method
  end;

  insert into public.client_payments(client_id,appointment_id,amount,discount_percent,method,date)
  values (v_appointment.client_id,p_appointment_id,p_service_total,0,v_method_label,v_today);

  return jsonb_build_object('already_paid',false,'balance_before',v_balance,'used_balance',v_used,'amount_due',v_due,'received',v_received,'change',v_change,'deposited',v_deposit,'balance_after',v_balance-v_used+v_deposit);
end;
$$;

revoke all on function public.complete_appointment_with_balance(bigint,integer,text,integer,boolean,boolean) from public, anon;
grant execute on function public.complete_appointment_with_balance(bigint,integer,text,integer,boolean,boolean) to authenticated;
