-- ZenFlow: таблица услуг + разрешение на удаление клиентов
-- Выполнить в Supabase → SQL Editor → Run (после schema.sql)

create table services (
  id bigint generated by default as identity primary key,
  name text not null,
  color text not null default '#7C9A86',
  duration integer not null default 60,
  price integer not null default 0,
  created_at timestamptz default now()
);

alter table services enable row level security;
create policy "allow all - services" on services for all using (true) with check (true);

insert into services (name, color, duration, price) values
('Классический массаж', '#7C9A86', 60, 4200),
('Спортивный массаж', '#B98572', 90, 5200),
('Лимфодренаж', '#9C8FB0', 60, 3800),
('Массаж лица', '#C6A15B', 45, 2800);
