-- ZenFlow: таблица записей — связывает клиентов и услуги в расписание
-- Выполнить в Supabase → SQL Editor → Run (после schema.sql и schema_02_services.sql)

create table appointments (
  id bigint generated by default as identity primary key,
  client_id bigint references clients(id) on delete set null,
  service_id bigint references services(id) on delete set null,
  date date not null,
  start_time text not null,
  duration integer not null default 60,
  price integer not null default 0,
  status text not null default 'planned', -- planned | done | cancelled
  notes text default '',
  created_at timestamptz default now()
);

alter table appointments enable row level security;
create policy "allow all - appointments" on appointments for all using (true) with check (true);

-- Демо-записи на сегодня — как было в моках, но теперь настоящие строки
insert into appointments (client_id, service_id, date, start_time, duration, price, status)
select c.id, s.id, current_date, '09:00', 60, 4200, 'done'
from clients c, services s where c.name = 'Марина Соколова' and s.name = 'Классический массаж'
union all
select c.id, s.id, current_date, '10:30', 90, 5200, 'done'
from clients c, services s where c.name = 'Игорь Плетнёв' and s.name = 'Спортивный массаж'
union all
select c.id, s.id, current_date, '13:00', 60, 3800, 'planned'
from clients c, services s where c.name = 'Анна Ким' and s.name = 'Лимфодренаж'
union all
select c.id, s.id, current_date, '14:00', 45, 2800, 'planned'
from clients c, services s where c.name = 'Дарья Ефимова' and s.name = 'Массаж лица'
union all
select c.id, s.id, current_date, '16:30', 60, 4200, 'planned'
from clients c, services s where c.name = 'Олег Крылов' and s.name = 'Классический массаж';
