import React, { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { ArrowLeft, Search, Plus, X, Check, ChevronLeft, ChevronRight } from "lucide-react";
import ThemeToggle from "../components/ThemeToggle";
import { getServices } from "../data/services";
import { getClients, getClientById, createClient } from "../data/clients";
import { getAppointmentById, getAppointmentServices, getAppointmentPayment, updateAppointmentPayment, createAppointment, updateAppointment, saveAppointmentServices, completeAppointment, fmtDate } from "../data/appointments";

const WEEKDAYS=["Пн","Вт","Ср","Чт","Пт","Сб","Вс"];
const KEYS=["mon","tue","wed","thu","fri","sat","sun"];
const DEFAULT_WEEK=KEYS.map(key=>({key,on:false,start:"10:00",end:"22:00",breakStart:null,breakEnd:null}));
function getWorkingHours(p,date){const w=p?.working_hours;if(Array.isArray(w)) return w.find(x=>x.key===KEYS[(date.getDay()+6)%7])||DEFAULT_WEEK[(date.getDay()+6)%7];const weekly=w?.weekly||DEFAULT_WEEK;return weekly.find(x=>x.key===KEYS[(date.getDay()+6)%7])||DEFAULT_WEEK[(date.getDay()+6)%7];}
function startOfWeek(d){const x=new Date(d);x.setDate(x.getDate()-((x.getDay()+6)%7));x.setHours(0,0,0,0);return x}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function pad(n){return String(n).padStart(2,"0")}
function timeToMin(t){const [h,m]=String(t||"10:00").split(":").map(Number);return h*60+m}
function minToTime(m){return `${pad(Math.floor(m/60))}:${pad(m%60)}`}
function weekDiff(a,b){return Math.round((startOfWeek(b)-startOfWeek(a))/(7*24*60*60*1000))}

export default function AppointmentForm(){
 const {mode}=useParams(); const id=mode==="new"?null:mode; const [params]=useSearchParams(); const navigate=useNavigate(); const today=useMemo(()=>new Date(),[]);
 const [services,setServices]=useState([]),[clients,setClients]=useState([]),[hours,setHours]=useState(null),[client,setClient]=useState(null),[selectedServices,setSelectedServices]=useState([]),[date,setDate]=useState(today),[timeMin,setTimeMin]=useState(600),[notes,setNotes]=useState(""),[payment,setPayment]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[query,setQuery]=useState(""),[quick,setQuick]=useState(false),[quickName,setQuickName]=useState(""),[quickPhone,setQuickPhone]=useState("");
 const monday=useMemo(()=>{const x=startOfWeek(today);x.setDate(x.getDate()+weekDiff(today,date)*7);return x},[today,date]); const week=useMemo(()=>Array.from({length:7},(_,i)=>addDays(monday,i)),[monday]);
 const duration=selectedServices.reduce((s,x)=>s+Number(x.duration||0),0),price=selectedServices.reduce((s,x)=>s+Number(x.price||0),0); const filtered=clients.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())).slice(0,7);
 const serviceNames=selectedServices.map(s=>s.name).filter(Boolean);
 useEffect(()=>{let dead=false;const cid=params.get("client");Promise.all([getServices(),getClients(),id?getAppointmentById(id):Promise.resolve(null),id?getAppointmentServices(id):Promise.resolve([]),id?getAppointmentPayment(id):Promise.resolve(null),!id&&cid?getClientById(cid):Promise.resolve(null)]).then(([sv,cl,a,as,p,linkedClient])=>{if(dead)return;setServices(sv);setClients(cl);if(a){if(a.clients)setClient({id:a.clients.id,name:a.clients.name});setDate(new Date(`${a.date}T12:00:00`));setTimeMin(timeToMin(a.start_time));setNotes(a.notes||"");setPayment(p);if(as?.length)setSelectedServices(as.map(x=>({id:x.service_id,duration:x.duration,price:x.price,name:x.services?.name,color:x.services?.color})));else if(a.services)setSelectedServices([a.services]);}else{const qd=params.get("date"),qt=params.get("time");if(qd)setDate(new Date(`${qd}T12:00:00`));if(qt)setTimeMin(timeToMin(qt));if(linkedClient)setClient({id:linkedClient.id,name:linkedClient.name});else if(cid){const c=cl.find(x=>String(x.id)===cid);if(c)setClient({id:c.id,name:c.name})}}setLoading(false)}).catch(()=>{if(!dead){setError("Не удалось загрузить данные");setLoading(false)}});return()=>{dead=true}},[id,params]);
 function toggleService(s){setSelectedServices(prev=>prev.some(x=>x.id===s.id)?prev.filter(x=>x.id!==s.id):[...prev,{id:s.id,name:s.name,color:s.color,duration:s.duration,price:s.price}])}
 function changeWeek(n){setDate(d=>addDays(d,n*7))} function selectDay(i){setDate(week[i])}
 async function addQuick(){if(!quickName.trim())return;try{const c=await createClient({name:quickName,phone:quickPhone});setClients(x=>[...x,c]);setClient({id:c.id,name:c.name});setQuick(false);setQuickName("");setQuickPhone("")}catch{window.alert("Не удалось создать клиента")}}
 async function save(){setError("");if(!client){setError("Выберите клиента");return}if(!selectedServices.length){setError("Выберите хотя бы одну услугу");return}setSaving(true);try{const payload={client_id:client.id,service_id:selectedServices[0].id,date:fmtDate(date),start_time:minToTime(timeMin),duration,price,notes};const a=id?await updateAppointment(id,payload):await createAppointment({...payload,status:"planned"});await saveAppointmentServices(a.id,selectedServices);if(payment)await updateAppointmentPayment(payment.id,price);navigate("/calendar")}catch{setError("Не удалось сохранить запись");setSaving(false)}}
 async function cancel(){if(!id||!window.confirm("Отменить запись?"))return;try{await updateAppointment(id,{status:"cancelled"});navigate("/calendar")}catch{setError("Не удалось отменить")}}
 async function complete(method){if(!id)return;setSaving(true);try{await completeAppointment({id,client_id:client?.id,price},method);navigate("/calendar")}catch{setError("Не удалось принять оплату");setSaving(false)}}
 if(loading)return <div className="min-h-screen bg-[var(--paper)] flex items-center justify-center text-sm text-[var(--ink-soft)]">Загружаем…</div>;
 return <div className="min-h-screen bg-[var(--paper)] text-[var(--ink)] font-sans"><div className="max-w-sm mx-auto pb-28">
  <div className="flex items-center justify-between px-5 pt-7 pb-2"><button onClick={()=>navigate(-1)} className="rounded-full p-2.5 bg-[var(--surface-alt)]"><ArrowLeft size={18}/></button><div className="text-lg font-serif">{id?"Редактирование записи":"Новая запись"}</div><ThemeToggle/></div>
  {payment&&<div className="mx-5 mt-4 rounded-2xl p-3 bg-[var(--moss-soft)] text-sm"><div className="flex items-center justify-between"><span className="font-medium">Оплачено</span><span className="font-mono">{Number(payment.amount).toLocaleString("ru-RU")} ₽</span></div><div className="text-xs mt-1 text-[var(--ink-soft)]">{payment.method}</div><div className="mt-2 pt-2 border-t border-[var(--line)]"><div className="text-xs font-medium mb-1">Услуги</div><div className="text-xs text-[var(--ink-soft)]">{serviceNames.length ? serviceNames.join(" · ") : "Услуги не найдены"}</div><div className="text-xs mt-1 text-[var(--ink-soft)]">{selectedServices.length} {selectedServices.length===1?"услуга":"услуг"} · {duration} мин</div></div><div className="text-xs mt-2 text-[var(--ink-soft)]">Оплата сохраняется даже при изменении даты, времени или состава услуг.</div></div>}
  <div className="mx-5 mt-5"><div className="text-sm font-medium mb-2 text-[var(--ink-soft)]">Клиент</div>{client?<div className="rounded-2xl p-3.5 flex justify-between bg-[var(--moss-soft)]"><div className="text-sm font-medium">{client.name}</div><button onClick={()=>setClient(null)} className="text-xs text-[var(--moss)]">Изменить</button></div>:<><div className="flex items-center gap-2 rounded-2xl px-3.5 py-2.5 bg-[var(--surface)] border border-[var(--line)]"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск клиента" className="flex-1 bg-transparent outline-none text-sm"/></div><div className="flex gap-2 mt-2 overflow-x-auto">{filtered.map(c=><button key={c.id} onClick={()=>setClient({id:c.id,name:c.name})} className="shrink-0 rounded-full px-3 py-2 text-sm bg-[var(--surface-alt)]">{c.name}</button>)}<button onClick={()=>setQuick(true)} className="shrink-0 rounded-full px-3 py-2 text-sm border border-dashed border-[var(--line)]"><Plus size={14} className="inline"/> Новый</button></div>{quick&&<div className="mt-2 rounded-2xl p-3 bg-[var(--surface)] border border-[var(--line)]"><input value={quickName} onChange={e=>setQuickName(e.target.value)} placeholder="Имя" className="w-full rounded-xl p-2 mb-2 bg-[var(--surface-alt)] outline-none"/><input value={quickPhone} onChange={e=>setQuickPhone(e.target.value)} placeholder="Телефон" className="w-full rounded-xl p-2 mb-2 bg-[var(--surface-alt)] outline-none"/><div className="flex gap-2"><button onClick={()=>setQuick(false)} className="flex-1 rounded-full py-2 bg-[var(--surface-alt)]">Отмена</button><button onClick={addQuick} className="flex-1 rounded-full py-2 bg-[var(--moss)] text-[var(--on-accent)]">Сохранить</button></div></div>}</>}</div>
  <div className="mx-5 mt-5"><div className="text-sm font-medium mb-2 text-[var(--ink-soft)]">Услуги <span className="text-xs">· можно выбрать несколько</span></div><div className="grid grid-cols-2 gap-2.5">{services.map(s=>{const active=selectedServices.some(x=>x.id===s.id);return <button key={s.id} onClick={()=>toggleService(s)} className="rounded-2xl p-3 text-left border" style={{background:active?`${s.color}26`:"var(--surface)",borderColor:active?s.color:"var(--line)"}}><span className="w-2.5 h-2.5 rounded-full inline-block" style={{background:s.color}}/><div className="text-sm font-medium mt-1">{s.name}</div><div className="text-xs text-[var(--ink-soft)]">{s.duration} мин · {s.price.toLocaleString("ru-RU")} ₽</div>{active&&<div className="text-[11px] mt-1 text-[var(--moss)]">Выбрано</div>}</button>})}</div>{selectedServices.length>0&&<div className="rounded-2xl p-3 mt-3 bg-[var(--surface-alt)] text-sm flex justify-between"><span>{selectedServices.length} услуг · {duration} мин</span><b>{price.toLocaleString("ru-RU")} ₽</b></div>}</div>
  <div className="mx-5 mt-5"><div className="flex items-center justify-between mb-3"><button onClick={()=>changeWeek(-1)} className="p-2 rounded-full bg-[var(--surface-alt)]"><ChevronLeft size={17}/></button><div className="text-sm font-medium capitalize">{date.toLocaleDateString("ru-RU",{month:"long",year:"numeric"})}</div><button onClick={()=>changeWeek(1)} className="p-2 rounded-full bg-[var(--surface-alt)]"><ChevronRight size={17}/></button></div><div className="flex justify-between">{week.map((d,i)=><button key={d.toISOString()} onClick={()=>selectDay(i)} className="w-9 rounded-xl py-2 flex flex-col items-center" style={{background:d.toDateString()===date.toDateString()?"var(--moss)":"transparent",color:d.toDateString()===date.toDateString()?"var(--on-accent)":"var(--ink-soft)"}}><span className="text-[10px]">{WEEKDAYS[i]}</span><span className="text-sm">{d.getDate()}</span></button>)}</div><div className="mt-3 flex items-center gap-2"><input type="time" value={minToTime(timeMin)} onChange={e=>setTimeMin(timeToMin(e.target.value))} className="flex-1 rounded-xl p-3 bg-[var(--surface)] border border-[var(--line)] font-mono"/><button onClick={()=>setDate(new Date())} className="rounded-xl px-3 py-3 bg-[var(--surface-alt)] text-sm">Сегодня</button></div></div>
  <div className="mx-5 mt-5"><div className="text-sm font-medium mb-2 text-[var(--ink-soft)]">Заметка</div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Например: меньше давления…" className="w-full min-h-24 rounded-2xl p-3 bg-[var(--surface)] border border-[var(--line)] outline-none text-sm"/></div>
  {error&&<div className="mx-5 mt-3 text-sm text-[var(--clay)]">{error}</div>}
  <div className="mx-5 mt-5 flex gap-2">{id&&<button onClick={cancel} className="rounded-full px-4 py-3 bg-[var(--clay-soft)]"><X size={16}/></button>}<button disabled={saving} onClick={save} className="flex-1 rounded-full py-3 font-medium" style={{background:"var(--moss)",color:"var(--on-accent)",opacity:saving?.6:1}}>{saving?"Сохраняем…":"Сохранить"}</button></div>
  {id&&!payment&&<div className="mx-5 mt-3 flex gap-2"><button onClick={()=>complete("Наличные")} className="flex-1 rounded-full py-2.5 text-sm bg-[var(--surface-alt)]"><Check size={14} className="inline mr-1"/> Оплатить наличными</button><button onClick={()=>complete("Карта")} className="flex-1 rounded-full py-2.5 text-sm bg-[var(--surface-alt)]">Оплатить картой</button></div>}
 </div></div>
}
